#!/usr/bin/env bash

# fail on errors
set -e

check() {
    local cmd="$1"
    
    if command -v "$cmd" >/dev/null 2>&1; then
        echo "$cmd"
        return 0
    else
        echo "error: '$cmd' not found" >&2
        return 1
    fi
}

get_make() {
    local cmd="${STMB_MAKE:-make}"
    check "$cmd"
}

get_compiledb() {
    local cmd="${STMB_COMPILEDB:-compiledb}"
    check "$cmd"
}

get_tio() {
    local cmd="${STMB_TIO:-tio}"
    check "$cmd"
}

get_openocd() {
    local cmd="${STMB_OPENOCD:-openocd}"
    check "$cmd"
}

get_project_name() {
    basename "$(ls | grep ".ioc")" ".ioc"
}

init() {
    cat << 'EOF' > stmb.mk
# This file serves to add new sources and vendor submodules (such as core-lib). It's
# a Makefile fragment thats included into the Makefile generated by CubeMX after all
# the CubeMX stuff has been loaded. Here you have access to all the Makefile variables
# and can change them anyway you want. Most commonly, you are going to be extending
# them like shown bellow. Other variables can be found in the original Makefile if needed.

# By extending `C_SOURCES` you can add your additional source files.
# C_SOURCES += \
# Core/Src/can.c \

# By extending `C_INCLUDES` you can add directory paths for includes.
# C_INCLUDES += \
# -ICore/SomeOtherDirectory

# Other useful variables are listed bellow

# For preprocessor defines
# C_DEFS += \

# Compiler flags
# CFLAGS += \

# Linker flags
# LDFLAGS += \

# Include the CoreLib as a submodule, see notes for the submodule initialization.
# include core-lib/stmb.mk
EOF

    cat << 'EOF' > stmb.conf
# This is also a bash script that should export the required or needed environment
# variables for the build system. It is automatically sourced if found in the project
# root.

# Family of microcontroller, info used by openocd in order to
# properly flash the code onto a mcu. The full list of supported hardware can be
# found in the installation directory of openocd, on Linux that being
# /usr/share/openocd/scripts/target. It needs to match the name of the file without
# the .cfg extension.
# export STMB_BOARD=stm32f0x

# Baudrate for the UART device communication. Only needed if
# tio is to be used for communication. If its not used, it can be left undefined.
# export STMB_BAUDRATE=115200
EOF
}

clean() {
    local make=$(get_make)

    $make clean
    rm compile_commands.json
}

build() {
    local make=$(get_make)
    local compiledb=$(get_compiledb)

    # add our custom sources and includes
    if ! grep -q "\-include stmb.mk" Makefile; then
        sed -i '/# list of objects/i -include stmb.mk' Makefile
    fi

    $compiledb $make
}

get_board() {
    if [[ "$STMB_BOARD" == "" ]]; then
        echo "error: board not found" >&2
        return 1
    fi

    echo "$STMB_BOARD"
    return 0
}

flash() {
    local openocd=$(get_openocd)
    local project_name=$(get_project_name)

    # note: if these are on the same line then 'set -e' does not work, so we have to separete them on two lines :/ idk, bash
    local board
    board=$(get_board)
    
    # TODO: make the actions customizable
    $openocd -f interface/stlink.cfg -f target/$board.cfg -c "program build/$project_name.elf verify reset exit"
}

get_baudrate() {
    local baudrate="${STMB_BAUDRATE:-115200}"

    echo "$baudrate"
}

uart() {
    local tio=$(get_tio)
    local baudrate=$(get_baudrate)

    # TODO: currently the device name is hardcoded since i dont have any boards at me right now. we should list all the
    # connected devices and grep through them to find the approprate one. consult milan for the right marks we should
    # look for here.
    $tio -b $baudrate /dev/ttyACM0

}

if [[ -f stmb.conf ]]; then
    source stmb.conf
fi

case "$1" in
    init)
        init
        ;;
    build)
        build
        ;;
    flash)
        flash
        ;;
    uart)
        uart
        ;;
    clean)
        clean
        ;;
    *)
        echo "usage: $0 {init|build|flash|uart|clean}" >&2
        exit 1
        ;;
esac
