# This files serves to add new sources and vendor submodules (such as core-lib). It's
# a Makefile fragment thats included into the Makefile generated by CubeMX after all
# the CubeMX stuff has been loaded. Here you have access to all the Makefile variables
# and can change them anyway you want. Most commonly, you are going to be extending
# them like shown bellow. Other variables can be found in the original Makefile if needed.

# By extending `C_SOURCES` you can add your additional source files.
C_SOURCES += \
app/src/app.c \
app/src/can.c \

# By extending `C_INCLUDES` you can add directory paths for includes.
C_INCLUDES += \
-Iapp/include

# Other useful variables are listed bellow

# For preprocessor defines
# C_DEFS += \

# Compiler flags
# CFLAGS += \

# Linker flags
# LDFLAGS += \
