# This is also a bash script that should export the required or needed environment
# variables for the build system. It is automatically sourced if found in the project
# root.

# Family of microcontroller, info used by openocd in order to
# properly flash the code onto a mcu. The full list of supported hardware can be
# found in the installation directory of openocd, on Linux that being
# /usr/share/openocd/scripts/target. It needs to match the name of the file without
# the .cfg extension.
export STMB_BOARD=stm32f0x

# Baudrate for the UART device communication. Only needed if
# tio is to be used for communication. If its not used, it can be left undefined.
# export STMB_BAUDRATE=115200
